### ISSUE TITLE
Request: Make some packages non internal or expose some needed methods

### ISSUE THREAD

**Issue by 0xVasconcelos** [datarhei/gosrt#50]
Hey! 

I'm trying to implement my own PubSub logic(like destroy all subscribers when a publisher disconnects, etc) and the problem is some important packages like `packet.Packet` are internal and the readPacket/writePackage methods are also internal, with that I would have to copy too many files to implement my logic. It makes sense?

Thanks!

**Comment by ioppermann** [comment]
Yes that makes sense. These packages are currently internal in order to have smaller API surface. Now that there seems to be some demand, it makes sense to open it up more.

**Comment by ioppermann** [comment]
All the internal packages are now public.
