### ISSUE TITLE
Irregular ACK sequence progression

### ISSUE THREAD

**Issue by 346** [datarhei/gosrt#67]
When performing load testing, there are times when the ACK sequence number returned from the gosrt listener becomes a lower value.This issue likely occurs when there is packet loss.

<img width="1393" alt="5e9f2274-ee98-47ad-9c83-ae6a2933ea4a_pcap" src="https://github.com/user-attachments/assets/54e226b6-b677-416e-a72f-5bb1244d636f">

[5e9f2274-ee98-47ad-9c83-ae6a2933ea4a.pcap.zip](https://github.com/user-attachments/files/16561496/5e9f2274-ee98-47ad-9c83-ae6a2933ea4a.pcap.zip)

**Comment by ioppermann** [comment]
@346 Thanks for pointing that out. I was an edge case where an older sequence number gets ACK'd. This has been fixed.
