### ISSUE TITLE
Feature Request: Different receiver and publisher tokens

### ISSUE THREAD

**Issue by SerethiX** [datarhei/gosrt#7]
In an environment where it would not be save to give the srt token to the receivers, it would be great to have separate tokens for publishing and a different token to receive the content.

`mode=publish,token:<shared-token>,secret-token:<secret-token>`
`mode=re quest,token:<shared-token>`

That way a malicious receiver would not be able to stream to the same channel once the publisher disconnects.

**Comment by ioppermann** [comment]
This is up to the implementation of the SRT server. The contributed server is only for demonstration purposes and can act as a starting point for your own implementation of a server.

If you are coming from our Restreamer project [datarhei/restreamer](https://github.com/datarhei/restreamer), then I can tell you that we're currently working on a solution that will solve this problem.
