### ISSUE TITLE
The client connects to the server without entering a passphrase

### ISSUE THREAD

**Issue by sinais54** [datarhei/gosrt#74]
I use the server in [contrib](https://github.com/datarhei/gosrt/tree/main/contrib) and set a passphrase in it. If I don't use the password in the URI part of the client, I can still connect to the server.
I use ffmpeg as a client

**Comment by ioppermann** [comment]
This is correct. With the server in `contrib` you can still send unencrypted streams even if you defined a passphrase. This is an implementation choice of this server. You can modify it in oder to reject unencrypted connections.

You can modify this behaviour here:
https://github.com/datarhei/gosrt/blob/d8162b5202cb59f3676d269e87c5863b8d460027/contrib/server/main.go#L171-L176
Check if a passphrase is given and then reject any request where `req.IsEncrypted()` is `false`.

Keep in mind that the passphrase/encryption is not meant for access control. For access control you can use the token, which needs to be placed in the `streamid`.
