### ISSUE TITLE
UnmarshalURL

### ISSUE THREAD

**Issue by TranscodingAddict** [datarhei/gosrt#75]
Hi,

it's more a question than an issue, but this can turn to an issue depending on the answer.

I have implemented a SRT using gosrt.
It handles connect/publish/subsribe/.... and acts as a listener.
It's based on the examples from the repo.

On the caller side i use ffmpeg than pushes a SRT stream using an output url like this:
srt://ip:port/?streamid=publish:app/[streamid']?auth=&latency=2000&recv_buffer_size=2097152&sndbuf=2097152

My question is to know if gosrt internally handles the parsing of the url parameters to apply these value to the connection config.
I found that this job seems to be done by UnmarshalURL, but I can't see UnmarshalURL being called anywhere.

Could you please help me understand how gosrt as a listener applies the parameters passed by the caller, if it's done of course?

Thanks a lot!

**Comment by ioppermann** [comment]
Because you are using ffmpeg on the caller side, ffmpeg is doing the parsing of the URL. The server using `gosrt` will never see this URL.

By using ffmpeg you have to stick to the syntax that ffmpeg requires. This command will show you all the options: `ffmpeg -h protocol=srt`. With ffmpeg you can either use the URL-like syntax. Then the `libsrt` will parse the URL. If you use the ffmpeg options instead, ffmpeg will set these options directly via the `libsrt` API.

**Comment by TranscodingAddict** [comment]
Thanks your quick answer!
So for instance using  -latency n or &latency=N on FFmpeg side with have the same effect, which is FFmpeg sending this value using the SRT protocol to the listener right ?

**Comment by ioppermann** [comment]
This is correct

**Comment by TranscodingAddict** [comment]
Wonderfull, could you please point me to the right gosrt source code file (and line maybe) where i can monitor the values sent by the caller ? Thanks!

**Comment by TranscodingAddict** [comment]
I'm sorry for all these questions, the root cause if that whatever latency size I choose, I get a lot of packet loss when pushing from FFmpeg to gosrt.
The network conditions are very good, I wonder where I miss something.

Thanks again for your support

**Comment by ioppermann** [comment]
Keep in mind that with ffmpeg you have to specify the latency in microseconds. If you want to have a latency of 500ms, you have to use `-latency 500000`.

**Comment by ioppermann** [comment]
SRT is based on UDP. Check that between the sender and receiver are no firewalls or anything else that deprioritzes UDP packets.

I can send from my Mac to a RaspberryPi running the contributed SRT server without packet loss over WiFi in the local network.

**Comment by TranscodingAddict** [comment]
Ok thanks for these recommendations! On FFmpeg side, is a high -latency the best thing to try to reduce the losses ?

**Comment by ioppermann** [comment]
Yes, to avoid losses, you have to increase the latency. This will increase the buffer in the server such that there's a bigger time window to wait for late or resent packets.
